[workspace]
resolver = "2"
members = [
    "crates/poddyclip",
    "crates/poddyclip-cli",
    "crates/poddyclip-plugin",
    "xtask",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Poddyclip Team"]
license = "UNLICENSED"

[profile.release]
lto = "thin"
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"
