[alias]
 xtask = "run --package xtask --release --"
build-cli = "build --release --no-default-features --features cli --bin poddyclip-cli"
build-plugin = "xtask bundle poddyclip --release"
run-cli = "run --release --no-default-features --features cli --bin poddyclip-cli --"
