[alias]
xtask = "run --package xtask --release --"
build-cli = "build --release -p poddyclip-cli"
build-plugin = "xtask bundle poddyclip-plugin --release"
run-cli = "run --release -p poddyclip-cli --"
