defmodule PoddyclipBackendWeb.Endpoint do
  use Sentry.PlugCapture
  use Phoenix.Endpoint, otp_app: :poddyclip_backend

  require Logger

  # Skip logging for health check endpoint to reduce noise from k8s probes
  plug :skip_health_logging

  defp skip_health_logging(%{request_path: "/health"} = conn, _opts) do
    Logger.disable(self())
    conn
  end

  defp skip_health_logging(conn, _opts), do: conn

  # Basic auth for pre-launch testing (enabled via SITE_PASSWORD env var)
  plug PoddyclipBackendWeb.Plugs.BasicAuth

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_poddyclip_backend_key",
    signing_salt: "MJ4V3fLh",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # WebSocket for React frontend job updates
  socket "/socket", PoddyclipBackendWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :poddyclip_backend,
    gzip: not code_reloading?,
    only: PoddyclipBackendWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    body_reader: {PoddyclipBackendWeb.CacheBodyReader, :read_body, []}

  plug Sentry.PlugContext

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug PoddyclipBackendWeb.Router
end
